server:
  servlet:
    context-path: "/api"
  port: 8080
spring:
  application:
    name: "fitness-system"
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis-plus:
  type-aliases-package: com.wsw.fitnesssystem.infrastructure.persistence.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
auth:
  jwt:
    access-secret: "84hQeGado6JIMKBNDJudeQuogatipj9xluip2moqvp3qLozvz043hDDTWcSuF8Fn"
    refresh-secret: "2ySXSQB9puHMYGOmMnykDH4fscjo7NIqNIpiG2SUWcxlvAfLv6WiCUWv590JeuE2"
    min-length: 32
    expire: 900
    refresh-expire: 604800
    issuer: "student-fitness"
    audience: "web-client"
  security:
    permit-all-patterns:
      - /auth/login
      - /auth/refresh
    bcrypt-strength: 6
  session:
    expire: 604800
    max-online-sessions: 3
  risk:
    max-fail-count: 5
    lock-duration-minutes: 30
    count-window-minutes: 30